config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  namespace :admin do
    resources :girls
  end

  namespace :manager do
    resources :girls do
      resources :products
    end
  end

  resources :products do
    collection do
      get :search
    end
  end

  resources :girls
  resource :cart
  resources :orders do
    member do
      get :approved
      post :execute
    end
  end

  root :to => "products#index"

end

app/models/cart.rb
class Cart
  attr_accessor :items

  def initialize
    @items = []
  end

  def add_item(product_id, quantity)
    product_id = product_id.to_i
    quantity = quantity.to_i

    product = Product.find(product_id) #check if product exist

    item = @items.find{ |x| x[:product_id] == product_id} #when exist

    if item
      item[:quantity] += quantity
    else
    @items << { product_id: product_id, quantity: quantity }
    end
  end

  def update(product_id, quantity)
    product_id = product_id.to_i
    quantity = quantity.to_i

    item = @items.find{ |x| x[:product_id] == product_id}

    item[:quantity] = quantity
    refresh
  end

  def remove(product_id)
    @items.delete_if{ |x| x[:product_id] == product_id.to_i }
  end

  def products
    @items.map{ |i|
      p = Product.find(i[:product_id])
      {
        product_id: p.id,
        title: p.title,
        price: p.price,
        quantity: i[:quantity],
        amount: p.price * i[:quantity].to_i
      }
    }
  end

  def count
    @items.count
  end

  def total
    products.map{ |p| p[:amount] }.sum
  end

  def clear
    @items = []
  end

  private

  def refresh
    @items.delete_if{ |x| x[:quantity].to_i <= 0 }
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show

  end

  def update
    failed_products = []
    params[:item].each do |product_id, quantity|
      @product = Product.find(product_id)
      if quantity.to_i > @product.quantity
        failed_products << @product
      end
    end

    if failed_products.empty?
      params[:item].each do |product_id, quantity|
        current_cart.update(product_id, quantity)
      end
      flash[:notice] = "修改數量成功"
    else
      product_names = failed_products.map{ |x| x.title }.join(", ")
      flash[:alert] = "#{product_names} 已超過商品數量"
    end

    redirect_to :back
  end

  def create
    current_cart.add_item(params[:product_id], params[:quantity] || 1)
    redirect_to :back
    flash[:notice] = "商品已加入購物車"
  end

  def destroy
    pid = params[:product_id]
    current_cart.remove(pid)
    flash[:notice] = "商品已移除"

    redirect_to :back
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.erb
<h2>購物車</h2>
<div class="pincart">
<%= form_tag "/cart", method: :patch do %>
<table class="table table-striped table-hover ">
  <thead>
    <tr>
      <th>#</th>
      <th>產品</th>
      <th>價錢</th>
      <th>數量</th>
      <th>總價</th>
    </tr>
  </thead>
  <tbody>
    <% current_cart.products.each do |i| %>
    <tr class="info">
      <td></td>
      <td><%= i[:title] %></td>
      <td><span class="price"><%= i[:price] %></span></td>
      <td>
        <%= number_field_tag "item[#{i[:product_id]}]", i[:quantity], :min => 0, :class => "qty" %>
        <%= link_to "Remove", cart_path(product_id: i[:product_id]), method: :delete %>
      </td>
      <td><%= i[:amount] %></td>
    </tr><% end %>
     <tr>
       <td><h5><strong>總共: </strong></h5></td>
       <td><h5><strong><span class="totalMoney"><%="$#{current_cart.total} NTD"%></span></strong></h5></td>
       <td></td>
       <td></td>
       <td></td>
     </tr>
  </tbody>
</table>
<%= submit_tag "更新數量" %>
  <p></p>
<% end %>
<%= button_to "購買", new_order_path, method: :get, :class => "btn btn-primary btn-lg" %>
</div>