config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  namespace :admin do
    resources :girls
  end

  namespace :manager do
    resources :girls do
      resources :products
    end
  end

  resources :products do
    collection do
      get :search
    end
  end

  resources :girls
  resource :cart
  resources :orders do
    member do
      get :approved
      post :execute
    end
  end

  root :to => "products#index"

end

app/models/girl.rb
class Girl < ActiveRecord::Base

  belongs_to :user
  has_many :products

  has_attached_file :avatar, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/controllers/admin/girls_controller.rb
class Admin::GirlsController < ApplicationController
  before_action :find_girl, only: [:show, :edit, :update, :destroy]
  before_action :admin_reqired
  before_action :authenticate_user!

  def index
    @girls = Girl.all
    @girl = Girl.new
    @product = Product.new
  end


  def create
    @girl = Girl.new(girl_params)
    if @girl.save
      redirect_to admin_girls_path
    end
  end

  def edit

  end

  def update
    if @girl.update(girl_params)
      redirect_to admin_girls_path
    end
  end

  def destroy
    @girl.destroy
    redirect_to admin_girls_path
  end

  private

  def find_girl
    @girl = Girl.find(params[:id])
  end

  def girl_params
    params.require(:girl).permit(:name, :avatar)
  end
end

app/controllers/girls_controller.rb
class GirlsController < ApplicationController

  def show
    @girl = Girl.find(params[:id])
  end
end

app/helpers/admin/girls_helper.rb
module Admin::GirlsHelper
end

app/helpers/girls_helper.rb
module GirlsHelper
end

app/views/girls/show.html.erb
<h1><%= "#{@girl.name}" %></h1>

<% @girl.products.each do |p| %>
<div class="row">

<div class="pin ">
<%= link_to (image_tag p.avatar.url), product_path(p) %>
  <div>
    <p><b><%= p.title %></b></p>
    <p>描述： <%= p.description %></p>
    <p>價錢： <%= p.price %></p>
    <p>數量： <%= p.quantity %></p>
    <%= button_to "加入購物車", cart_path(product_id: p.id, quantity: 1), :class => "btn btn-primary" %>

    <% if admin_reqired %>
    <%= link_to "edit", edit_product_path(p) %>
    <%= link_to "destroy", product_path(p), method: :delete %>
    <% end %>
  </div>
</div>
<%end %>