config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  namespace :admin do
    resources :girls
  end

  namespace :manager do
    resources :girls do
      resources :products
    end
  end

  resources :products do
    collection do
      get :search
    end
  end

  resources :girls
  resource :cart
  resources :orders do
    member do
      get :approved
      post :execute
    end
  end

  root :to => "products#index"

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :girl

  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos

  has_many :cart_items
  has_many :carts, through: :cart_item

  has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

end

app/controllers/manager/products_controller.rb
class Manager::ProductsController < ApplicationController

  before_action :find_girl
  before_action :find_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = @girl.products.all
    @product = Product.new
    @photo = @product.photos.new
  end

  def show

  end

  def create
    @product = @girl.products.build(product_params)
    if @product.save
      redirect_to manager_girl_products_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @product.update(product_params)
      redirect_to manager_girl_products_path
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to manager_girl_products_path
  end

  private

  def find_girl
    @girl = Girl.find(params[:girl_id])
  end

  def find_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :girl_id, :quantity, :photos_attributes => [:images])
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :find_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show, :search]
  def index
    @products = Product.all
    @girls = Girl.all

    @product = Product.new
    @photo = @product.photos.build

  end

  def show
    @photos = @product.photos
  end

  def create
    @product = Product.create(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @product.update(product_params)
      redirect_to products_path
    else
      render :edit
    end
  end

  def destroy
    @product.destroy
    redirect_to products_path
  end

  def search
    if params[:q].nil?
      @products = []
    else
      @products = Product.search(params[:q]).records
    end
  end

  private

  def find_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:title, :description, :price, :girl_id, :quantity, :avatar)
  end
end

app/helpers/manager/products_helper.rb
module Manager::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper

end

app/views/products/_form.html.erb
<%= simple_form_for @product, :html => {:multipart => true} do |f| %>
  <%= f.input :title, label: "product name: " %>
  <%= f.input :description, label: "description: " %>
  <%= f.input :price, label: "price: " %>
  <%= f.input :quantity, label: "quantity: " %>
  <%= f.input :avatar, :as => :file %>

  <%= f.association :girl, as: :radio_buttons %>
  <%= f.button :submit %>
<% end %>

app/views/products/index.html.erb
<div id="main">
    <div id="reel">
        <div id="header" class="item" data-width="400">
            <div class="inner">

                <h1>STYO.ME</h1>
                <h1>時尚達人</h1>
            </div>
        </div>
        <% @girls.each do |g| %>
        <article class="item thumb" data-width="282">
            <h2><%= g.name %></h2>
            <%= link_to (image_tag g.avatar.url), girl_path(g)  %>
        </article>
        <% end %>
    </div>
</div>

</div>

app/views/products/search.html.erb
<h1>Product Search</h1>

<div class="pin">
<ul>
  <% @products.each do |product| %>
  <li>
    <%= link_to (image_tag product.avatar.url), product_path(product) %>
  </li>
  <li>
    <%= link_to product.title, product_path(product.id) %>
  </li>
  <% end %>
</ul></div>

app/views/products/show.html.erb
<div class="row">
<div class="pin">
<h1><%= @product.title %></h1>
<%= image_tag @product.avatar.url(:medium) %>
<ul>
  <li><%= @product.description %></li>
<!--   <li><%= @product.quantity %></li> -->
  <strong><p>優惠價: $<%= @product.price %></p></strong>
  <%= button_to "加入購物車", cart_path(product_id: @product.id, quantity: 1), :class => "btn btn-primary" %>
</ul>

<ul><% @photos.each do |photo| %>
  <li><%= image_tag photo.images.url %></li>
<% end %>
<div class="fb-like" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
</ul>
<div class="fb-comments" data-href="<%= request.original_url %>" data-numposts="5" data-colorscheme="light"></div>

</div>
</div>