config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  namespace :admin do
    resources :girls
  end

  namespace :manager do
    resources :girls do
      resources :products
    end
  end

  resources :products do
    collection do
      get :search
    end
  end

  resources :girls
  resource :cart
  resources :orders do
    member do
      get :approved
      post :execute
    end
  end

  root :to => "products#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Styome beta</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-static-top" role="navigation">
    <div class="container">
    <div class="navbar-header">

      <%= link_to (image_tag "/images/logo2.png"), products_path, :class => "navbar-brand" %>
      <ul class="nav navbar-nav">
        <li>Beta</li>

      </ul>
      <!-- search   -->
      <ul class="nav navbar-nav">
        <li><br>
          <%= form_tag search_products_path, method: :get do %>
            <%= label_tag "找商品" %>
            <%= text_field_tag :q, params[:q] %>
            <%= submit_tag "搜尋", name: nil %>
          <% end %>
        </li>
      </ul>
    </div>

    <ul class="nav navbar-nav navbar-right">
      <!-- fb login -->

      <% if current_user %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="false"><%= "Hi! #{current_user.email}" %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li>
              <%= link_to("logout", destroy_user_session_path, method: :delete)%>
            </li>
            <li>
               <%= link_to("edit password", edit_registration_path(:user)) %>
            </li></ul>
      <% else %>
          <ul class="nav navbar-nav">
          <li><%= link_to "Facebook Login", user_omniauth_authorize_path(:facebook)%></li>
<!--           <li>
            <%= link_to("sign up", new_registration_path(:user)) %>
          </li>
          <li>
            <%= link_to("log in", new_session_path(:user)) %>
          </li> -->
        </ul>
      <% end %>
       <!-- 後台 -->
      <% if admin_reqired %>
      <li><%= link_to "後台管理", admin_girls_path %> </li>
      <% end %>
      </li>
      <!-- 購物車 -->
        <li id="event_area"><%= link_to "購物車(#{current_cart.count})", cart_path(current_cart) %></li>
      <!-- 訂單 -->
        <li><%= link_to "訂單", orders_path %></li>
      </ul>

      </div>
  </nav>


<div class="container">

      <% if flash[:notice] %>
        <div class="alert alert-dismissable alert-info">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <%= flash[:notice] %>
        </div>
      <% end %>

      <% if flash[:alert] %>
        <div class="alert alert-dismissable alert-warning">
          <button type="button" class="close" data-dismiss="alert">×</button>
          <h5>Warning!</h5>
          <%= flash[:alert] %>
        </div>
        </div>
      <% end %>

<%= yield %>
</div>
<div id="fb-root"></div>
</body>
<script>
  window.fbAsyncInit = function() {
    // init the FB JS SDK
    FB.init({
      appId      : '366379540206005',                        // App ID from the app dashboard
      status     : true,                                 // Check Facebook Login status
      version    : 'v2.0',
      xfbml      : true                                  // Look for social plugins on the page
    });

    // Additional initialization code such as adding Event Listeners goes here
  };</script>
</html>